function Food(name, ingredients, protein, fat, fibre, ash, carbs) {
    this.name = name;
    this.ingredients = ingredients;
    this.protein = protein;
    this.fat = fat;
    this.fibre = fibre;
    this.ash = ash;
    this.carbs = carbs;
}

let foodsList = [
    new Food('James Well Beloved Adult', 'Lamb Meal(23.5%), Brown Rice(20.0%), White Rice(19.7%), Barley, Whole Linseed, Lamb Fat(3.5%), Lamb Gravy(2.9%), Sugar Beet Pulp, Alfalfa Meal, Omega Oil Supplement*, Sodium Chloride, Seaweed(0.5%), Potassium Chloride, Chicory Extract(0.1%), Calcium Carbonate, Yucca Extract(0.02%) * from Sunflower and Fish Oils', 21.7, 11.4, 3.3, 9.6, 54.0),
    new Food('Wainwrights Dry Adult Large Breed', 'Brown Rice(37%), Turkey(30%) (Turkey Meat Meal, Turkey Gravy), Barley Meal (10%), Potato Protein(7%), Rapeseed Oil(7%), Linseed(4%), Sugar Beet Pulp(2%), Alfalfa(0.8%), Minerals, (Includes Yucca Extract 200mg/kg, Marigold Meal 50mg/kg, Rosemary Extract 5mg/kg), Seaweed (0.5%), Glucosamine (0.1%), Chondroitin Sulphate(0.1%).', 30.0, 11.1, 4.4, 6.7, 47.8),  
    new Food('Aatu 80/20', '80% Chicken(Includes 50% Chicken, 30% Dehydrated Chicken) Sweet Potato, Chickpeas, Peas, Lucerne, Chicken Stock, Salmon Oil, Carrots, Tomato, Chicory, Tapioca, Apple, Pear, Cranberry, Blueberry, Mulberry, Orange, Bilberry, Cowberry, Parsley, Peppermint, Spirulina, Seaweed, Oregano, Sage, Marjoram, Thyme, Chamomile, Rosehip, Stinging Nettle, Yucca, Marigold, Aniseed, Fenugreek, Cinnamon, Hip & Joint Care (Glucosamine 178mg/kg, MSM 178mg/kg, Chondroitin 125mg/kg).', 34.8, 17.4, 3.3, 7.6, 40.2),
    new Food('Akela 80/20', 'Freshly Prepared Chicken 22%, Dehydrated Chicken 15%, Dehydrated Herring 10%, Potato 9%, Sweet Potato 7%, Dehydrated Turkey 7%, Freshly Prepared Chicken Liver 7%, Dehydrated Salmon 6%, Chicken Fat 4%, Freshly Prepared Free-Range Egg 3%, Freshly Prepared Salmon 3%, Chicken Stock 2%, Pea Fibre 2%, Salmon Oil 1%, Chickpeas, Lentils, Alfalfa/Lucerne, Vitamins, Minerals, Prebiotic FOS (1900 mg/kg), Apple, Organic Peas, Organic Spinach, Organic Pumpkin, Organic Carrot, Camomile, Marigold Petals, Aniseed & Fenugreek, Peppermint, Joint Support [Glucosamine (170mg/kg), MSM (170mg/kg), Chondroitin Sulphate (120mg/kg)], Yucca Schidigera Extract, Seaweed, Cranberry, Dandelion, Pear, Blueberry, Fennel, Rosemary (0.04%), Burdock Root, Rosehips, Organic Honey (0.01%), Garlic (0.01%).', 42.4, 20.1, 3.3, 12.0, 25.5),
    new Food('AniForte PureNature Junior Menu', "86.0% Chicken (60.0% from Chicken Heart, Chicken Meat, Chicken Liver, Chicken Stomach, Chicken Neck and 26.0% from Meat Stock), 4.0% Carrots, 3.0% Courgettes, 2.0% Fennel, 2.0% Potatoes, 1.0% Raspberries, 1.0% Apples, 0.1% Egg Shell Powder, 0.1% Herbs (Dandelion, Yarrow, Fennel, Camomile), 0.1% Yeast, 0.1% Linseed, 0.1% Rapeseed Oil, 0.1% Desiccated Coconut, 0.1% Silica, 0.1% Spirulina, 0.1% Omega-3 Extract, 0.1% Seaweed Calcium.", 40.4, 24.4, 2.4, 8.8, 26.4),
    new Food("Bow & Dog Complete Dog Food", "Poultry 71% (Including Freshly Prepared Chicken 36%, Dried Chicken 22%, Freshly Prepared Turkey 11%, ChickenClick to see what we think about Chicken in dog food Stock 1%, Dried Duck 1%), Sweet Potato 11.8%, Potato 6.2%, Fish 9% (Freshly Prepared Salmon 4%, Freshly Prepared Pollock 4%, Salmon Oil 1%), PeaClick to see what we think about Peas in dog food Fibre, Dried Egg, Minerals, Vitamins, Linseed, Seaweed, Dried Apple, Dried Carrot, Dried Spinach, Dried Cranberry, Tomato Pomace, Glucosamine 180mg/kg, Methylsulphonylmethane 180 mg/kg, Chondroitin Sulphate 125 mg/kg, Camomile Powder, Peppermint, Dried Bilberry, Grapeseed Extract, Green Tea Extract, Dried Dandelion, Burdock Root Powder, Aniseed & Fenugreek, Marigold, Ginseng, Thyme, Majoram, Oregano, Parsley, Sage.", 37.0, 19.6, 3.0, 8.7, 37.3),
    new Food("Eden Dog Food", "Chicken 19%, Chicken 18% (from Dried Chicken), Salmon 15%, Herring 12.5% (from Dried Herring), Sweet Potato 12%, Chicken Fat 4.5%, Duck 4% (from Dried Duck), Tapioca 3.5%, Whole Egg 2.5% (from Dried Egg), Chicken Liver 2.5%, White Fish 2%, Pea Fibre 2%, Lucerne, Chickpea, Minerals & Vitamins, Carrot, Spinach, Apple, Rosehips, Camomile, Burdock Root, Seaweed, , Aniseed & Fenugreek, Fructooligosaccharides (461 mg/kg), Glucosamine (341mg/kg), MSM (341mg/kg), Chondroitin (240mg/kg), Thyme, Marjoram, Oregano, Parsley, Sage.", 44.6, 19.6, 3.3, 10.3, 25.5),
];